// Real data only. web/data/api-snapshot.json (chain index) + Hermes session 20260927_201540_61b710 (signal readings); generated by the video build
window.OATH = {
 "_source": "web/data/api-snapshot.json (chain index) + Hermes session 20260927_201540_61b710 (signal readings); generated by the video build",
 "seq": 2,
 "strat": "acceptance_test",
 "why": "OPERATOR_TEST: acceptance test, 3/4 signals",
 "thesis": {
  "agent": "9jxuhhv7pe3iL8tFfDvS1TuRRC18LCyT7g6c5wR332bY",
  "conf": "0.50",
  "entry": "123.243260",
  "horizon_min": "15",
  "in_mint": "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
  "mkt": "SOL/USDC",
  "out_mint": "So11111111111111111111111111111111111111112",
  "seq": "2",
  "side": "long",
  "size_usd": "1.00",
  "stop": "119.545962",
  "strat": "acceptance_test",
  "tp": "129.405423",
  "ts": "2026-09-27T19:16:44Z",
  "v": "1",
  "why": "OPERATOR_TEST: acceptance test, 3/4 signals"
 },
 "canonical": "{\"agent\":\"9jxuhhv7pe3iL8tFfDvS1TuRRC18LCyT7g6c5wR332bY\",\"conf\":\"0.50\",\"entry\":\"123.243260\",\"horizon_min\":\"15\",\"in_mint\":\"EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v\",\"mkt\":\"SOL/USDC\",\"out_mint\":\"So11111111111111111111111111111111111111112\",\"seq\":\"2\",\"side\":\"long\",\"size_usd\":\"1.00\",\"stop\":\"119.545962\",\"strat\":\"acceptance_test\",\"tp\":\"129.405423\",\"ts\":\"2026-09-27T19:16:44Z\",\"v\":\"1\",\"why\":\"OPERATOR_TEST: acceptance test, 3/4 signals\"}",
 "salt": "5270cdaf826cefb078d02d229ec0cf1180ca24fccda44cc96b1d48feff11c7aa",
 "digest": "2d88fbe85b444aaa81c7e71024dbb3dafe1beef98ad154cffaa9ef73c7c41d6b",
 "tampered": {
  "entry": "121.000000",
  "canonical": "{\"agent\":\"9jxuhhv7pe3iL8tFfDvS1TuRRC18LCyT7g6c5wR332bY\",\"conf\":\"0.50\",\"entry\":\"121.000000\",\"horizon_min\":\"15\",\"in_mint\":\"EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v\",\"mkt\":\"SOL/USDC\",\"out_mint\":\"So11111111111111111111111111111111111111112\",\"seq\":\"2\",\"side\":\"long\",\"size_usd\":\"1.00\",\"stop\":\"119.545962\",\"strat\":\"acceptance_test\",\"tp\":\"129.405423\",\"ts\":\"2026-09-27T19:16:44Z\",\"v\":\"1\",\"why\":\"OPERATOR_TEST: acceptance test, 3/4 signals\"}",
  "digest": "afee48a919099abdf6efda0480ef554f4320ee985dd8bf4ddae74d28197b30bd"
 },
 "commit": {
  "slot": 451088313,
  "time": "19:16:47 UTC",
  "sig": "5etvhtz2aC7XgxnTUv8VxyKFrV2ajWexnRvv1uCboKXfCy6cLtvALXjCKDBXLi5RucxiQMotaYKJUGj8fVQB72gY"
 },
 "swap": {
  "slot": 451088333,
  "time": "19:16:52 UTC",
  "sig": "39D21wHHH3TpSN8ktkfHyLXjrF6KL87K6PKTDdE5F5drFDJdrTRPDDfb3UGKfYFdAos1xdExAKUjohNChc5TDqsr",
  "spent": "1.000000 USDC",
  "received": "0.008113454 SOL"
 },
 "exit": {
  "slot": 451091850,
  "time": "19:32:37 UTC",
  "reason": "expiry",
  "spent": "0.008113454 SOL",
  "received": "0.998162 USDC"
 },
 "reveal": {
  "slot": 451091870,
  "time": "19:32:43 UTC",
  "sig": "2zsUxmwANsmzUe5doagut2cVMzHgBHYfg3ajYCuBEqpaC7Bit142EgGYbj2u77DhK7bG4r3SbFVABLfqn4Krva7x"
 },
 "pnl_usd": "-0.003068",
 "held_s": 945,
 "signals": [
  {
   "name": "24h trend",
   "reading": "+1.70%",
   "state": "agree"
  },
  {
   "name": "Momentum",
   "reading": "1h +0.45% \u00b7 4h +1.12%",
   "state": "agree"
  },
  {
   "name": "Risk appetite",
   "reading": "neutral, trend + momentum hold",
   "state": "agree"
  },
  {
   "name": "SOL flow",
   "reading": "no SOL-specific signal",
   "state": "missing"
  }
 ],
 "signals_time": "27 Sep 2026 \u00b7 19:16 UTC"
};
